### PR TITLE
Updated Lobby, made sure prod url is used in prod, closes #32

### LINKED ISSUE #32: Ensure websocket connects in Production

### PR DESCRIPTION
**Pull request by carolernst-uzh**

### CODE REVIEW

**Review by trofej — COMMENTED** [review]
Everything looks fine to me, however why did you delete: history.push(`/game/play/${gameId}`);?

**Review by trofej — APPROVED** [review]
But i think is fine, looks at least fine to me :]

**Comment by carolernst-uzh** [comment]
@trofej it's not deleted, I moved it up to line 42 so it would apply to both host and guest. The reason this is important is that only either the host or the guest should call startGame, not both, otherwise one overwrites the changes of the other and we get a mess. This had somehow gotten lost in previous updates.

**Comment by trofej** [comment]
> @trofej it's not deleted, I moved it up to line 42 so it would apply to both host and guest. The reason this is important is that only either the host or the guest should call startGame, not both, otherwise one overwrites the changes of the other and we get a mess. This had somehow gotten lost in previous updates.

Okk, nice, makes sense :]

**Pull request merged**
